# Generated by Django 5.1.1 on 2024-10-02 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')])),
                ('type', models.TextField(choices=[('PAYMENT', 'Payment'), ('FINE', 'Fine')])),
                ('borrowing_id', models.IntegerField()),
                ('session_url', models.URLField(verbose_name='Url to stripe payment session')),
                ('session_id', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
