# Generated by Django 5.1.1 on 2024-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('cover', models.TextField(choices=[('HARD', 'Hard'), ('SOFT', 'Soft')])),
                ('daily_fee', models.DecimalField(decimal_places=5, max_digits=10)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
