# Generated by Django 5.1.1 on 2024-09-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
