# Generated by Django 5.1.1 on 2024-09-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='amount',
            new_name='inventory',
        ),
    ]
