# Generated by Django 5.1.1 on 2024-09-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_service', '0003_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Inventory',
        ),
    ]
