# Generated by Django 5.1.1 on 2024-09-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_service', '0004_remove_book_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Cover',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Daily_fee',
            new_name='daily_fee',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
