# Generated by Django 5.1.1 on 2024-09-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowing',
        ),
    ]
