# Generated by Django 5.1.1 on 2024-09-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings_service', '0003_alter_borrowing_actual_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
